export const skillList = [
  { name: 'JavaScript', progress: 99 },
  { name: 'PostgreSQL', progress: 79 },
  { name: 'TypeScript', progress: 89 },
  { name: 'Redux', progress: 69 },
  { name: 'React.js', progress: 99 },
  { name: 'HTML', progress: 99 },
  { name: 'Node.js', progress: 85 },
  { name: 'CSS', progress: 99 },
  { name: 'MySQL', progress: 79 },
  { name: 'Sass', progress: 89 },
  { name: 'Prisma', progress: 79 },
  { name: 'Git', progress: 99 },
  { name: 'StyledComp', progress: 89 },
  { name: 'C#', progress: 50 },
  { name: 'PHP', progress: 50 },
];